name: Vps
on:
  workflow_dispatch:
jobs:
  secure-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: ssh userr
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-server sudo
          
        
          sudo useradd -m -s /bin/bash UserX
          
          echo 'UserX ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/UserX
          
          sudo mkdir -p /home/UserX/.ssh
          echo '${{ secrets.SSH_PUBLIC_KEY }}' | sudo tee /home/UserX/.ssh/authorized_keys
          sudo chown -R UserX:UserX /home/UserX/.ssh
          sudo chmod 700 /home/UserX/.ssh
          sudo chmod 600 /home/UserX/.ssh/authorized_keys
          
          sudo sed -i 's/#PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
          
          sudo systemctl restart ssh

      #Download
      - name: Dwonalod tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=vps-${{ github.run_id }}
          tsIP=$(tailscale ip -4 | head -n 1)
          echo "TAILSCALE_IP=$tsIP" >> $GITHUB_ENV
          echo "✅ Tailscale IP: $tsIP"

      - name: Display info 
        run: |
          echo "vps is run"
          echo "-------------------------------------"
          echo "📍 tailscale ip: $TAILSCALE_IP"
          echo "👤 ssh User: UserX"
          echo "🔑 Ex  connect, use this command "

          echo "ssh -i ~/.ssh/vps_key UserX@$TAILSCALE_IP"
          echo "-------------------------------------"

      - name: running use Loop
        run: |
          while true; do
            echo "VPS running"
            sleep 300
          done
